### ISSUE TITLE
DavMail unable to fetch/push events from/to Exchange calendar

### ISSUE THREAD

**Issue by ldesousa** [mguessan/davmail#10]
I set up DavMail about one year ago on various Ubuntu systems (home and office) to access my work calendar (Exchange). It has worked flawlessly, until last weekend. Since then all instances are failing to fetch/push updates to the calendar. In the logs there are multiple exceptions like the one below:

```
2018-11-27 08:02:38,167 ERROR [CaldavConnection-42806] davmail.exchange.ExchangeSession  - Exchange login exception: 500 Internal Server Error at https://login.wur.nl/adfs/ls/wia?wa=wsignin1.0&wtrealm=https://webmail.wur.nl/owa/&wctx=rm=0&id=passive&ru=%2fowa%2f&wct=2018-11-27T07:02:38Z&client-request-id=16a8ab49-2de8-49c4-e51b-0080010000b0
2018-11-27 08:02:38,167 ERROR [CaldavConnection-42806] davmail  - Exchange login exception: 500 Internal Server Error at https://login.wur.nl/adfs/ls/wia?wa=wsignin1.0&wtrealm=https://webmail.wur.nl/owa/&wctx=rm=0&id=passive&ru=%2fowa%2f&wct=2018-11-27T07:02:38Z&client-request-id=16a8ab49-2de8-49c4-e51b-0080010000b0
davmail.exception.DavMailException: Exchange login exception: 500 Internal Server Error at https://login.wur.nl/adfs/ls/wia?wa=wsignin1.0&wtrealm=https://webmail.wur.nl/owa/&wctx=rm=0&id=passive&ru=%2fowa%2f&wct=2018-11-27T07:02:38Z&client-request-id=16a8ab49-2de8-49c4-e51b-0080010000b0
	at davmail.exchange.ExchangeSession.<init>(ExchangeSession.java:271)
	at davmail.exchange.dav.DavExchangeSession.<init>(DavExchangeSession.java:500)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:147)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:90)
	at davmail.caldav.CaldavConnection.run(CaldavConnection.java:168)
```
I am able to access my calendar through the webmail application, and my phone (Android) is also able to fetch/push calendar events. Therefore this is not an issue with the server.

Thanks for reading.

**Comment by mguessan** [comment]
You are redirected to ADFS trying to access OWA, please use direct EWS endpoint instead:
https://webmail.wur.nl/ews/exchange.asmx

Make sure you set mode to EWS

**Comment by ldesousa** [comment]
Thank you, that indeed got DavMail working again. Why did the previous stopped working?

**Comment by mguessan** [comment]
Well, I don't know, maybe something changed on ADFS form that broke DavMail form authentication... which is no longer needed with recent Exchange versions.
