### ISSUE TITLE
Unexpected EOF in prolog

### ISSUE THREAD

**Issue by GuillaumeMaurice** [mguessan/davmail#109]
Hi, 
since yesterday I'm unable to fech new mails. 
I get the following error in the logs : 
```
2020-05-09 14:45:08,077 ERROR [ImapConnection-52861] davmail.exchange.ews.EWSMethod  - Error while parsing soap response: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:693)
	at com.ctc.wstx.sr.BasicStreamReader.handleEOF(BasicStreamReader.java:2213)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2119)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1175)
	at davmail.exchange.ews.EWSMethod.processResponseStream(EWSMethod.java:1209)
	at davmail.exchange.ews.EWSMethod.processResponseBody(EWSMethod.java:1176)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1749)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at davmail.exchange.ews.EwsExchangeSession.internalExecuteMethod(EwsExchangeSession.java:2993)
	at davmail.exchange.ews.EwsExchangeSession.executeMethod(EwsExchangeSession.java:2960)
	at davmail.exchange.ews.EwsExchangeSession.checkEndPointUrl(EwsExchangeSession.java:229)
	at davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:249)
	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:198)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:186)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:99)
	at davmail.imap.ImapConnection.run(ImapConnection.java:140)
2020-05-09 14:45:08,078 ERROR [ImapConnection-52861] davmail.exchange.ews.EWSMethod  - com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0] Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
2020-05-09 14:45:08,751 WARN  [ImapConnection-52861] davmail.exchange.ExchangeSession  - All network interfaces down or host unreachable !
2020-05-09 14:45:08,751 DEBUG [ImapConnection-52861] davmail.exchange.ExchangeSession  - java.io.IOException: Ews endpoint not available at /ews/exchange.asmx status 403
java.io.IOException: Ews endpoint not available at /ews/exchange.asmx status 403
	at davmail.exchange.ews.EwsExchangeSession.checkEndPointUrl(EwsExchangeSession.java:242)
	at davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:249)
	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:198)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:186)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:99)
	at davmail.imap.ImapConnection.run(ImapConnection.java:140)
2020-05-09 14:45:08,751 INFO  [ImapConnection-52861] davmail.connection  - FAILED - 0:0:0:0:0:0:0:1:52861 guillaume.maurice@ericsson.com
2020-05-09 14:45:08,751 ERROR [ImapConnection-52861] davmail  - All network interfaces down or host unreachable !
2020-05-09 14:45:08,752 DEBUG [ImapConnection-52861] davmail  - > 1 NO LOGIN failed
2020-05-09 14:45:08,754 DEBUG [ImapConnection-52861] davmail  - < LOGIN ********

```
Details of the setup and of what I know : 
I'm trying to connect to my company Office365 mails, I've been using Devmail for a year without issue to connect Thunderbird there without any issue despite the MFA being active. ( I just have to enter my login/password + OTP everytime I start TB ) 
The above logfile comes from Davmail 5.3.1. I tried to upgrade to 5.5.1 but it didn't change anything, I received the same log error. ( actually from my point of view it was worse, I wasn't getting the davmail popups prompting for the login, password and OTP. )
Computer  : Windows 10 1809, Davmail, Latest Thunderbird.
I'm not certain it's something that changed at Microsoft or if it's something that got changed through a group policy on my laptop. ( especially since there's been no warning of any changes )

**Comment by GuillaumeMaurice** [comment]
Apparently It self fixed itself this morning. So no point investigating further. 

Side note : Other people with a different setup ( Linux and Evolution ) reported that they couldn't fetch mail too, after I posted here.
