### ISSUE TITLE
Davmail hangs on manual O365 authentication

### ISSUE THREAD

**Issue by ermin-sakic** [mguessan/davmail#121]
Following the attempt to manually log-in into Office 365 using provided link, pressing Open / or blue highlighted text results in a frozen window with the attached error.

![image](https://user-images.githubusercontent.com/5068504/88657047-8f59f100-d0d1-11ea-801c-90e13a790507.png)

I can, however, reproduce this only on a single machine. All of my machines are running Ubuntu 20.04 with appropriate packages and OpenJDK 1.8.0_252. This is a multimonitor setup.

```java
(SWT:99254): GLib-GIO-WARNING **: 12:48:31.636: unable to send notifications through org.freedesktop.Notifications: GDBus.Error:org.freedesktop.DBus.Error.FileExists: Unit xfce4-notifyd.service failed to load properly: File exists.
java.lang.Error
	at org.eclipse.swt.graphics.Device.logProc(Device.java:741)
	at sun.awt.X11.XDesktopPeer.gnome_url_show(Native Method)
	at sun.awt.X11.XDesktopPeer.launch(XDesktopPeer.java:118)
	at sun.awt.X11.XDesktopPeer.browse(XDesktopPeer.java:107)
	at java.awt.Desktop.browse(Desktop.java:385)
	at davmail.ui.browser.AwtDesktopBrowser.browse(AwtDesktopBrowser.java:41)
	at davmail.ui.browser.DesktopBrowser.browse(DesktopBrowser.java:49)
	at davmail.ui.browser.DesktopBrowser.browse(DesktopBrowser.java:95)
	at davmail.exchange.auth.O365ManualAuthenticatorDialog.lambda$getButtonPanel$2(O365ManualAuthenticatorDialog.java:131)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at davmail.exchange.auth.O365ManualAuthenticatorDialog.<init>(O365ManualAuthenticatorDialog.java:123)
	at davmail.exchange.auth.O365ManualAuthenticator.lambda$authenticate$0(O365ManualAuthenticator.java:101)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mguessan** [comment]
This error is related to SWT, please check that you have the same package version as your other machines.

A workaround may be to disable SWT completely, check launch script for details:
https://github.com/mguessan/davmail/blob/master/src/bin/davmail

**Comment by mguessan** [comment]
Reviewing old open tickets.

Implementation changed a lot since this ticket, preferred configuration is now latest SWT with best support for embedded browser and tray icon.

Feel free to open a new ticket against recent releases if you have any issues.
