### ISSUE TITLE
Processing message failed. Status: 80040111. When accepting invitation.

### ISSUE THREAD

**Issue by jschwartzenberg** [mguessan/davmail#155]
When I accept an invitation, I get the message "Processing message failed. Status: 80040111." in Thunderbird. Further Thunderbird shows:
```
Status Code: 2147746065, The request cannot be processed.

Server Replied with 503
```

On the DavMail side I get a this in the log file:
```
Date:			Wed Mar 31 09:58:58 CEST 2021 (1617177538951)
Thread:		CaldavConnection-20093
Message #:	1
Level:		ERROR
NDC:			
Category:	davmail
Message:		ErrorCalendarMeetingRequestIsOutOfDate The meeting request is out of date. The calendar couldn't be updated. 
 request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013_SP1"/></soap:Header><soap:Body><m:CreateItem SendMeetingInvitations="SendToAllAndSaveCopy" MessageDisposition="SendAndSaveCopy"><m:SavedItemFolderId><t:DistinguishedFolderId Id="sentitems"/></m:SavedItemFolderId><m:Items><t:AcceptItem><t:ReferenceItemId Id="AAMkADI5MGFkMTEzLTc0NWQtNGNhMi04ZDM0LThjMWQ3MzgyNTk4YwBGAAAAAACe2ZJ5owOsQZqykOHgsadbBwCdYhEFRbmqRoXKSjGRVc4+AAAAAAEMAACdYhEFRbmqRoXKSjGRVc4+AAMNwNGMAAA=" ChangeKey="CwAAABYAAACdYhEFRbmqRoXKSjGRVc4+AAMMv4xZ"/></t:AcceptItem></m:Items></m:CreateItem></soap:Body></soap:Envelope>
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
Thrown:
davmail.exchange.ews.EWSException: ErrorCalendarMeetingRequestIsOutOfDate The meeting request is out of date. The calendar couldn't be updated. 
 request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013_SP1"/></soap:Header><soap:Body><m:CreateItem SendMeetingInvitations="SendToAllAndSaveCopy" MessageDisposition="SendAndSaveCopy"><m:SavedItemFolderId><t:DistinguishedFolderId Id="sentitems"/></m:SavedItemFolderId><m:Items><t:AcceptItem><t:ReferenceItemId Id="AAMkADI5MGFkMTEzLTc0NWQtNGNhMi04ZDM0LThjMWQ3MzgyNTk4YwBGAAAAAACe2ZJ5owOsQZqykOHgsadbBwCdYhEFRbmqRoXKSjGRVc4+AAAAAAEMAACdYhEFRbmqRoXKSjGRVc4+AAMNwNGMAAA=" ChangeKey="CwAAABYAAACdYhEFRbmqRoXKSjGRVc4+AAMMv4xZ"/></t:AcceptItem></m:Items></m:CreateItem></soap:Body></soap:Envelope>
	at davmail.exchange.ews.EWSMethod.checkSuccess(EWSMethod.java:778)
	at davmail.exchange.ews.EwsExchangeSession.internalExecuteMethod(EwsExchangeSession.java:2997)
	at davmail.exchange.ews.EwsExchangeSession.executeMethod(EwsExchangeSession.java:2960)
	at davmail.exchange.ews.EwsExchangeSession$Event.createOrUpdate(EwsExchangeSession.java:2079)
	at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2672)
	at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:2658)
	at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:299)
	at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
	at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
```

The server is O365.

**Comment by jschwartzenberg** [comment]
Version of DavMail: 5.5.1-3299.

**Comment by mguessan** [comment]
This one is tricky: I guess you accept meeting from your inbox right ?
If the meeting was changed by the sender in the mean time, you will get this error.

I also noticed we get a lot more errors in calendar since last Thunderbird updates.
What I would try in this case:
- force calendar sync
- accept meeting from calendar instead of inbox

**Comment by mguessan** [comment]
Closing old outdated ticket, we definitely had some issues with meetings and shared calendars, hopefully fixed now.
