### ISSUE TITLE
Java version mismatch

### ISSUE THREAD

**Issue by jdpiguet** [mguessan/davmail#156]
I am using OpenJDK on Ubuntu "Ubuntu 18.04.5 LTS".
Mail client is Thunderbird, with O365Interactive.

`easjdp@elx7941006k:~$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
easjdp@elx7941006k:~$ `

Davmail fails to authenticate:
`Thread:		ImapConnection-49648
Message #:	31
Level:		ERROR
NDC:			
Category:	davmail
Message:		Authentication failed Timed out waiting for interactive authentication
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
Thrown:
davmail.exception.DavMailException: Authentication failed Timed out waiting for interactive authentication
	at davmail.exchange.auth.O365InteractiveAuthenticator.authenticate(O365InteractiveAuthenticator.java:165)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:183)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:99)
	at davmail.imap.ImapConnection.run(ImapConnection.java:140)
`

I see the following when starting it from shell:
`easjdp@elx7941006k:~$ Exception in thread "AWT-EventQueue-1" java.lang.UnsupportedClassVersionError: javafx/beans/value/ObservableValue has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at davmail.exchange.auth.O365InteractiveAuthenticator.lambda$authenticate$0(O365InteractiveAuthenticator.java:123)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

**Comment by jdpiguet** [comment]
Switching to Oracle java is a workaround:

`easjdp@elx7941006k:~$ /opt/java/64/jre1.8.0_291/bin/java -version
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b09, mixed mode)
easjdp@elx7941006k:~$ 

`

**Comment by mguessan** [comment]
You probably have OpenJFX 11 installed and try to use it with OpenJDK 8, this will obviously not work.

Note that OpenJFX is no longer embedded in latest OpenJDK/Oracle JDK

In order to get latest OpenJFX at the moment is seems that the best approach is to get it from Azul:
https://api.azul.com/zulu/download/community/v1.0/bundles/latest/binary/?jdk_version=15&ext=tar.gz&os=linux&arch=x86&hw_bitness=64&bundle_type=jre&features=fx

**Comment by mguessan** [comment]
Already answered. In addition we now have an SWT based embedded browser implementation not dependent on OpenJFX.

Closing ticket.
