### ISSUE TITLE
ERROR [CaldavConnection-48156] davmail  - java.lang.NullPointerException

### ISSUE THREAD

**Issue by Ri0n** [mguessan/davmail#16]
```
2018-12-27 12:56:34,448 ERROR [CaldavConnection-48156] davmail  - java.lang.NullPointerException
java.lang.NullPointerException
        at davmail.exchange.ews.EwsExchangeSession$Event.buildFieldUpdates(EwsExchangeSession.java:1731)
        at davmail.exchange.ews.EwsExchangeSession$Event.createOrUpdate(EwsExchangeSession.java:1998)
        at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2694)
        at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:3211)
        at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:290)
        at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:228)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:171)
```
It's with some 5.0.0-trunk version. I didn't try the latest trunk though.

Same version worked properly w/o restarts yesterday. So I guess something is changed on server side.

**Comment by Ri0n** [comment]
just tried the latest trunk. same problem

```
2018-12-27 13:02:31,336 ERROR [CaldavConnection-48278] davmail  - java.lang.NullPointerException
java.lang.NullPointerException
        at davmail.exchange.ews.EwsExchangeSession$Event.buildFieldUpdates(EwsExchangeSession.java:1731)
        at davmail.exchange.ews.EwsExchangeSession$Event.createOrUpdate(EwsExchangeSession.java:1998)
        at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2694)
        at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:3211)
        at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:290)
        at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:228)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:171)
```

**Comment by Ri0n** [comment]
just restarted both davmail and Thunderbird. seems working now.

**Comment by Ri0n** [comment]
it seems it starts crashing when I click Dismiss on calendar events notifications. Just noticed it again.

**Comment by mguessan** [comment]
Looks like you have a broken event with missing end date => workaround available in trunk

**Comment by Ri0n** [comment]
thanks! unfortunately I'll be unable to test the fix since I already removed the event via web interface.

**Comment by mguessan** [comment]
Closing issue then

**Comment by mguessan** [comment]
This is not the same issue, best practice is to open a separate ticket for a separate issue.

Anyway, your client tries to remove end date from event and fails => you can check Caldav content to investigate further.

**Comment by Ri0n** [comment]
I'm not sure I can do this in Thunderbird. Basically I just click "Dismiss" and see this error.

**Comment by Ri0n** [comment]
I'll open another issue
