### ISSUE TITLE
What i make wrong.. how see free/busy time for someone's calendars?

### ISSUE THREAD

**Issue by x09** [mguessan/davmail#167]
We use Exchange 2007 and 2013 and last davmail with thunderbird.

The user does not see free/busy time in someone else's calendar if he does not have explicit access rights. 

_As example_
BOSS have a personal calendar. BOSS shared calendar for EMPLOYEE1.
EMPLOYEE1 can see all events, free/busy time.
Other (EMPLOYEE2,EMPLOYEE3...EMPLOYEE99) does not see anything.. I just want see busy time on BOSS's calendar.
This is bug, or feature?

**Comment by aschaap** [comment]
With M365 at least, Thunderbird will show free/busy for people who have not explicitly shared their calendar with you after adding their email to the list of people to invite to an event, via its scheduling assistant (see https://support.mozilla.org/en-US/kb/inviting-other-people-events). This should let EMPLOYEE{2-99} in your example see whether BOSS is busy or free.

**Comment by x09** [comment]
My question about Microsoft Exchange. With third party Thunderbird extensions, like https://github.com/ExchangeCalendar/exchangecalendar/releases, work fine, but slowly..

**Comment by x09** [comment]
As example, 

![2021-07-26_10-40](https://user-images.githubusercontent.com/1303927/126938685-c01bd9df-0290-4f63-858f-d5f227bc1b1c.png)

1. add my boss calendar
2. I don't see any events..

**Comment by x09** [comment]
upgrade to 6.0. and get errors

`2021-07-26 15:08:58,565 DEBUG [davmail.caldav.CaldavServer] davmail  - Connection from /127.0.0.1 on port 1080
2021-07-26 15:08:58,565 INFO  [davmail.caldav.CaldavServer] davmail.connection  - CONNECT - 127.0.0.1:41356 
2021-07-26 15:08:58,566 DEBUG [CaldavConnection-41356] davmail  - < PROPFIND /users/usCAL-DAV-USER%40mydomain.ru/calendar/ HTTP/1.1
2021-07-26 15:08:58,568 DEBUG [CaldavConnection-41356] davmail  - < Host: localhost:1080
2021-07-26 15:08:58,569 DEBUG [CaldavConnection-41356] davmail  - < User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Thunderbird/78.12.0
2021-07-26 15:08:58,569 DEBUG [CaldavConnection-41356] davmail  - < Accept: text/xml
2021-07-26 15:08:58,569 DEBUG [CaldavConnection-41356] davmail  - < Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
2021-07-26 15:08:58,570 DEBUG [CaldavConnection-41356] davmail  - < Accept-Encoding: gzip, deflate
2021-07-26 15:08:58,570 DEBUG [CaldavConnection-41356] davmail  - < Accept-Charset: utf-8,*;q=0.1
2021-07-26 15:08:58,570 DEBUG [CaldavConnection-41356] davmail  - < Content-Type: text/xml; charset=utf-8
2021-07-26 15:08:58,571 DEBUG [CaldavConnection-41356] davmail  - < Content-Length: 306
2021-07-26 15:08:58,572 DEBUG [CaldavConnection-41356] davmail  - < Depth: 0
2021-07-26 15:08:58,573 DEBUG [CaldavConnection-41356] davmail  - < Origin: http://localhost:1080
2021-07-26 15:08:58,573 DEBUG [CaldavConnection-41356] davmail  - < Authorization: ********
2021-07-26 15:08:58,574 DEBUG [CaldavConnection-41356] davmail  - < Connection: keep-alive
2021-07-26 15:08:58,575 DEBUG [CaldavConnection-41356] davmail  - < Pragma: no-cache
2021-07-26 15:08:58,576 DEBUG [CaldavConnection-41356] davmail  - < Cache-Control: no-cache
2021-07-26 15:08:58,576 DEBUG [CaldavConnection-41356] davmail.caldav.CaldavConnection  - < <?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D='DAV:' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:CS='http://calendarserver.org/ns/'><D:prop><D:resourcetype/><D:owner/><D:current-user-principal/><D:supported-report-set/><C:supported-calendar-component-set/><CS:getctag/></D:prop></D:propfind>
2021-07-26 15:08:58,577 DEBUG [CaldavConnection-41356] davmail.exchange.ExchangeSession  - Got session davmail.exchange.ews.EwsExchangeSession@5c12140d from cache
2021-07-26 15:08:58,586 DEBUG [CaldavConnection-41356] davmail.http.DavGatewaySSLSocketFactory  - createSocket ex.mydomain.ru 443
2021-07-26 15:08:58,653 DEBUG [CaldavConnection-41356] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: exchangecookie][value: f0b6e78dc8f24d06b677bd74544c4de2][domain: ex.mydomain.ru][path: /][expiry: null]
2021-07-26 15:08:58,653 DEBUG [CaldavConnection-41356] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: X-BackEndCookie][value: S-1-5-21-3196609985-636931310-2637777318-51267=u56Lnp2ejJqBncibnMvJyJ3Sncucx9LLzcmd0p2Zxp7SnZvMm86bm57Ky57GgYHNz83O0s/H0s3Kq87Pxc/HxcrH][domain: ex.mydomain.ru][path: /ews][expiry: Wed Aug 25 15:08:58 YEKT 2021]
2021-07-26 15:08:58,655 INFO  [CaldavConnection-41356] davmail.connection  - LOGON - 127.0.0.1:41356 sh-MY-USER-NAME
2021-07-26 15:08:58,703 DEBUG [CaldavConnection-41356] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: exchangecookie][value: f0b6e78dc8f24d06b677bd74544c4de2][domain: ex.mydomain.ru][path: /][expiry: null]
2021-07-26 15:08:58,703 DEBUG [CaldavConnection-41356] davmail.http.HttpClientAdapter  - Add cookie [version: 0][name: X-BackEndCookie][value: S-1-5-21-3196609985-636931310-2637777318-51267=u56Lnp2ejJqBncibnMvJyJ3Sncucx9LLzcmd0p2Zxp7SnZvMm86bm57Ky57GgYHNz83O0s/H0s3Kq87Pxc/HxcrH][domain: ex.mydomain.ru][path: /ews][expiry: Wed Aug 25 15:08:58 YEKT 2021]
2021-07-26 15:08:58,703 DEBUG [CaldavConnection-41356] davmail.exchange.ews.EWSMethod  - ErrorFolderNotFound
2021-07-26 15:08:58,704 ERROR [CaldavConnection-41356] davmail  - ErrorFolderNotFound The specified folder could not be found in the store. 
 request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013"/></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:ExtendedFieldURI PropertyTag="0x10f3" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x670a" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x6752" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x360a" PropertyType="Boolean"/><t:ExtendedFieldURI PropertyTag="0x6751" PropertyType="Integer"/><t:FieldURI FieldURI="folder:DisplayName"/><t:ExtendedFieldURI PropertyTag="0x3613" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x3008" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x3602" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x3603" PropertyType="Integer"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="calendar"><t:Mailbox><t:EmailAddress>usCAL-DAV-USER@mydomain.ru</t:EmailAddress></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>
davmail.exchange.ews.EWSException: ErrorFolderNotFound The specified folder could not be found in the store. 
 request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013"/></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:ExtendedFieldURI PropertyTag="0x10f3" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x670a" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x6752" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x360a" PropertyType="Boolean"/><t:ExtendedFieldURI PropertyTag="0x6751" PropertyType="Integer"/><t:FieldURI FieldURI="folder:DisplayName"/><t:ExtendedFieldURI PropertyTag="0x3613" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x3008" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x3602" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x3603" PropertyType="Integer"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="calendar"><t:Mailbox><t:EmailAddress>usCAL-DAV-USER@mydomain.ru</t:EmailAddress></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>
        at davmail.exchange.ews.EWSMethod.checkSuccess(EWSMethod.java:802)
        at davmail.exchange.ews.EwsExchangeSession.internalExecuteMethod(EwsExchangeSession.java:2933)
        at davmail.exchange.ews.EwsExchangeSession.executeMethod(EwsExchangeSession.java:2895)
        at davmail.exchange.ews.EwsExchangeSession.internalGetFolder(EwsExchangeSession.java:1103)
        at davmail.exchange.ews.EwsExchangeSession.internalGetFolder(EwsExchangeSession.java:61)
        at davmail.exchange.ExchangeSession.getFolder(ExchangeSession.java:845)
        at davmail.caldav.CaldavConnection.sendFolderOrItem(CaldavConnection.java:697)
        at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:290)
        at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
2021-07-26 15:08:59,708 DEBUG [CaldavConnection-41356] davmail  - > HTTP/1.1 503 Service Unavailable
2021-07-26 15:08:59,708 DEBUG [CaldavConnection-41356] davmail  - > Server: DavMail Gateway 6.0.0-trunk
2021-07-26 15:08:59,708 DEBUG [CaldavConnection-41356] davmail  - > DAV: 1, calendar-access, calendar-auto-schedule, calendarserver-private-events, addressbook
2021-07-26 15:08:59,708 DEBUG [CaldavConnection-41356] davmail  - > Date: Mon, 26 Jul 2021 10:08:59 +0000
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > Expires: Mon, 26 Jul 2021 10:08:59 +0000
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > Cache-Control: private, max-age=0
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > Content-Type: text/plain;charset=UTF-8
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > Connection: close
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > Content-Length: 1345
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail  - > 
2021-07-26 15:08:59,709 DEBUG [CaldavConnection-41356] davmail.caldav.CaldavConnection  - > ErrorFolderNotFound The specified folder could not be found in the store. 
 request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013"/></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:ExtendedFieldURI PropertyTag="0x10f3" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x670a" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x6752" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x360a" PropertyType="Boolean"/><t:ExtendedFieldURI PropertyTag="0x6751" PropertyType="Integer"/><t:FieldURI FieldURI="folder:DisplayName"/><t:ExtendedFieldURI PropertyTag="0x3613" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x3008" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x3602" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x3603" PropertyType="Integer"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="calendar"><t:Mailbox><t:EmailAddress>usCAL-DAV-USER@mydomain.ru</t:EmailAddress></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>
2021-07-26 15:08:59,709 INFO  [CaldavConnection-41356] davmail.connection  - DISCONNECT - 127.0.0.1:41356 
`

**Comment by mguessan** [comment]
Reviewing old open tickets.

This one references FREE/BUSY but tries to access the calendar directly, not FREE/BUSY information.

In Thunderbird FREE/BUSY is accessed when creating a meeting with attendees. This is different from direct access to calendar that indeed requires access rights on target calendar.

Closing ticket
