### ISSUE TITLE
Cannot run davmail, getting  JSONObject["sCtx"] not found exceptien

### ISSUE THREAD

**Issue by filip-machala** [mguessan/davmail#172]
Hello,

I am trying to setup davmail with O365. I am using mode davmail.mode=O365Modern. I am getting error: 
```
2021-08-04 08:45:16,630 DEBUG [ImapConnection-35736] davmail.exchange.ExchangeSession  - java.io.IOException: org.codehaus.jettison.json.JSONException: JSONObject["sCtx"] not found. JSONObject["sCtx"] not found.
java.io.IOException: org.codehaus.jettison.json.JSONException: JSONObject["sCtx"] not found. JSONObject["sCtx"] not found.
        at davmail.exchange.auth.O365Authenticator.authenticate(O365Authenticator.java:238)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:182)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:93)
        at davmail.imap.ImapConnection.run(ImapConnection.java:128)
```
Can you please help me how to solve this?

Best regards
Filip Machala

**Comment by filip-machala** [comment]
I am adding more detailed logs here.

`2021-08-05 09:24:41,285 WARN  [ImapConnection-59812] davmail.exchange.ExchangeSession  - All network interfaces down or host unreachable !
2021-08-05 09:24:41,285 DEBUG [ImapConnection-59812] davmail.exchange.ExchangeSession  - java.io.IOException: org.codehaus.jettison.json.JSONException: JSONObject["sCtx"] not found. JSONObject["sCtx"] not found.
java.io.IOException: org.codehaus.jettison.json.JSONException: JSONObject["sCtx"] not found. JSONObject["sCtx"] not found.
        at davmail.exchange.auth.O365Authenticator.authenticate(O365Authenticator.java:238)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:182)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:93)
        at davmail.imap.ImapConnection.run(ImapConnection.java:128)
2021-08-05 09:24:41,285 INFO  [ImapConnection-59812] davmail.connection  - FAILED - 127.0.0.1:59812 ***@***.***
2021-08-05 09:24:41,285 ERROR [ImapConnection-59812] davmail  - All network interfaces down or host unreachable !
2021-08-05 09:24:41,286 DEBUG [ImapConnection-59812] davmail  - > DAGN1 NO LOGIN Kerberos authentication failed
2021-08-05 09:24:41,297 INFO  [ImapConnection-59812] davmail.connection  - DISCONNECT - 127.0.0.1:59812
`

**Comment by andreafrati1969** [comment]
Same error after an year from issue opening. Someone can help us ?

**Comment by logological** [comment]
I am experiencing the same error with `davmail.mode=O365Modern`.  I tried changing this to `O365Interactive` and got yet another different error message.  Finally I was able to get DavMail to connect using `O365Manual`, so this might also be a workaround for others.

**Comment by mguessan** [comment]
Reviewing old open tickets.

Issue with O365Modern is it's difficult to handle all the various tenant configurations with external Idp providers (ADFS, Okta, Ping, ...). Current implementation tries to handle at least default MFA factors like PhoneAppOTP, PhoneAppNotification, OneWaySMS.

We even have embedded TOTP support now!

However @logological is correct the most reliable authentication path is interactive with O365Interactive or the failover O365Manual.

This ticket is too outdated to match lines, feel free to reopen against latest version.
