### ISSUE TITLE
O365Modern don't support two possible way of WFA

### ISSUE THREAD

**Issue by SPT-EV** [mguessan/davmail#229]
Hello O365Modern don't support two possible way of WFA
```
2022-08-31 14:17:44,733 INFO  [main] davmail  - DavMail Gateway 6.0.1-3390 listening on POP port 1110 IMAP port 1143 
2022-08-31 14:17:45,062 DEBUG [CheckRelease] davmail.http.HttpClientAdapter  - GET http://davmail.sourceforge.net/version.txt
2022-08-31 14:17:45,483 DEBUG [CheckRelease] davmail.DavGateway  - DavMail released version: 6.0.1-3390
2022-08-31 14:17:52,796 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /ip.ip.ip.ip on port 1143
2022-08-31 14:17:52,812 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - ip.ip.ip.ip:21802 
2022-08-31 14:17:52,843 DEBUG [ImapConnection-21802] davmail.http.DavGatewaySSLSocketFactory  - createSocket outlook.office365.com 443
2022-08-31 14:17:53,655 DEBUG [ImapConnection-21802] davmail.exchange.ExchangeSession  - Test configuration status: 401
2022-08-31 14:17:53,655 DEBUG [ImapConnection-21802] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 6.0.1-3390 server ready
2022-08-31 14:17:53,780 DEBUG [ImapConnection-21802] davmail  - < LOGIN ********
2022-08-31 14:17:53,780 DEBUG [ImapConnection-21802] davmail.exchange.auth.O365Authenticator  - https://login.microsoftonline.com/...
2022-08-31 14:17:53,780 DEBUG [ImapConnection-21802] davmail.http.HttpClientAdapter  - GET https://login.microsoftonline.com/...
2022-08-31 14:17:53,796 DEBUG [ImapConnection-21802] davmail.http.DavGatewaySSLSocketFactory  - createSocket login.microsoftonline.com 443
2022-08-31 14:17:54,483 DEBUG [ImapConnection-21802] davmail.http.HttpClientAdapter  - ...
2022-08-31 14:17:54,499 DEBUG [ImapConnection-21802] davmail.exchange.auth.O365Authenticator  - Config={"arrUserProofs":[{"authMethodId":"OneWaySMS","data":"OneWaySMS","display":"+XX XXXXXXXX00","isDefault":false,"isLocationAware":false},{"authMethodId":"TwoWayVoiceMobile","data":"TwoWayVoiceMobile","display":"+XX XXXXXXXX00","isDefault":false,"isLocationAware":false}],...
2022-08-31 14:17:54,499 DEBUG [ImapConnection-21802] davmail.exchange.auth.O365Authenticator  - Authentication method: OneWaySMS
2022-08-31 14:17:54,499 DEBUG [ImapConnection-21802] davmail.exchange.auth.O365Authenticator  - Authentication method: TwoWayVoiceMobile
2022-08-31 14:17:54,530 WARN  [ImapConnection-21802] davmail.exchange.ExchangeSession  - All network interfaces down or host unreachable !
2022-08-31 14:17:54,530 DEBUG [ImapConnection-21802] davmail.exchange.ExchangeSession  - java.io.IOException: MFA authentication methods not supported
java.io.IOException: MFA authentication methods not supported
	at davmail.exchange.auth.O365Authenticator.handleMfa(O365Authenticator.java:389)
	at davmail.exchange.auth.O365Authenticator.authenticate(O365Authenticator.java:205)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:182)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
	at davmail.imap.ImapConnection.run(ImapConnection.java:128)
2022-08-31 14:17:54,530 INFO  [ImapConnection-21802] davmail.connection  - FAILED - ip.ip.ip.ip:21802 xxx@yyyy.com
2022-08-31 14:17:54,530 ERROR [ImapConnection-21802] davmail  - All network interfaces down or host unreachable !
2022-08-31 14:17:54,530 DEBUG [ImapConnection-21802] davmail  - > C1 NO LOGIN failed
2022-08-31 14:17:57,108 DEBUG [ImapConnection-21802] davmail  - < C2 LOGOUT
2022-08-31 14:17:57,108 DEBUG [ImapConnection-21802] davmail  - > * BYE Closing connection
2022-08-31 14:17:57,108 DEBUG [ImapConnection-21802] davmail  - > C2 OK LOGOUT completed
2022-08-31 14:17:57,108 INFO  [ImapConnection-21802] davmail.connection  - DISCONNECT - ip.ip.ip.ip:21802 
2022-08-31 14:19:20,346 INFO  [davmail.imap.ImapServer] davmail.connection  - DISCONNECT - ip.ip.ip.ip:21802
```

**Comment by SPT-EV** [comment]
Change the MFA to only Application Microsoft Authenticator pour Mobile for spécific user instead of Phone Number (SMS/Voice)
