### ISSUE TITLE
Loading calendar in Thunderbird fails with stacktrace

### ISSUE THREAD

**Issue by pvdspoel22** [mguessan/davmail#266]
Upon initial startup of Thunderbird one of my accounts in TB fails to load its calendar thru davmail.
Davmail produces the same stacktrace for 3 threads:

Exception in thread "CaldavConnection-59650" java.lang.StackOverflowError
	at java.base/java.lang.StringUTF16.checkBoundsBeginEnd(StringUTF16.java:1478)
	at java.base/java.lang.StringUTF16.putCharsSB(StringUTF16.java:1191)
	at java.base/java.lang.AbstractStringBuilder.appendChars(AbstractStringBuilder.java:1708)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:634)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:217)
	at davmail.exchange.ICSBufferedWriter.writeLine(ICSBufferedWriter.java:61)
.
.
.

With this last line repeated about 1000 times. 

Versions:
TB - 102.7.1 
Davmail - 6.0.1

**Comment by ifrh** [comment]
I can not reproduce it with DavMail 6.2.2 and TB 128.7.0esr .
