### ISSUE TITLE
ErrorNonExistentMailbox Mailbox does not exist

### ISSUE THREAD

**Issue by divansantana** [mguessan/davmail#295]
Hi

When using a config with `davmail.mode=O365Interactive` set, after the oauth login.microsoft.com prompt I get something like this:

```
DavMail configuration exception: Connect exception:
davmail.exchange.ews.EWSException ErrorNonExistentMailbox Mailbox does
not exist.  request: <soap:Envelope
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion
Version="Exchange2013_SP1"/></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape></m:FolderShape><m:FolderIds><t:DistinguishedFolderId
Id="root"/></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>
```

I'm suspecting, it's because the companies exchange/AD is integrated into o365.  The calendar and teams for instance is o365 based, as is the oauth integration.  However, the actual mailbox, doesn't sit in o365 outlook, only on premise on the exchange server.

I'm suspecting davmail is looking for my mailbox on o365 and saying it's not there.

The URL `davmail.url=https://outlook.thecompany.com/owa/` when I open it in a browser, does display the local exchange server's OWA page with the emails.  Any idea what else I can do to get this to work?

**Comment by divansantana** [comment]
Either that, or perhaps it's related to the companies domain name changing.

**Comment by mguessan** [comment]
Maybe, a quick to check this is to try to access calendar over Caldav, please try:

http://localhost:1080/users/user@company.com/calendar

According to the message above the authentication succeeds, now need to find the right mailbox name

**Comment by divansantana** [comment]
When I try that, the web page returns `Exchange login exception: Not Found` and logs say:

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
2023-10-01 18:45:53,141 INFO  [davmail.caldav.CaldavServer] davmail.connection  - CONNECT - 127.0.0.1:48954
2023-10-01 18:46:20,461 WARN  [CaldavConnection-48954] org.apache.http.client.protocol.ResponseProcessCookies  - Invalid cookie header: "Set-Cookie: AzureAppProxyPreauthSessionCookie_56db8f93-efa4-406f-ab67-0221b97da76e_3d69ea83-2cb7-467f-827b-3ef6dcfacc66_1.4=4|Ze0omG/kKdd/D5QTXFSGq2MoiSF2AMDzu++dMO0R8np5Gf9X8eGPbFs7Z5PdRkSDFdp2T4kn4IR3JU0zn34AQkf9RRqXPA32HHowMLfIup/+/WXty4k7h2MJn6cqBTDQFAnj1rT7FhDNd9L0a6jHIxT/H+R7KFvyCfbRW5dWpwWJLwIfPYOZ3reD20mXdqlwbClolRRoDL1Dy/Bmq7S7BmK+WdKfmZyNaCfNQn47HjuOOzKW6vgVu1WIAFGu666K3o2OFKVlKxDnux/2StBx+lIS/6d3zTFCSgYDw5bu2oM=; expires=Sun, 01 Oct 2023 16:56:20 GMT; path=/; Secure; SameSite=None". Invalid 'expires' attribute: Sun, 01 Oct 2023 16:56:20 GMT
2023-10-01 18:46:20,709 WARN  [CaldavConnection-48954] org.apache.http.client.protocol.ResponseProcessCookies  - Invalid cookie header: "Set-Cookie: AzureAppProxyPreauthSessionCookie_56db8f93-efa4-406f-ab67-0221b97da76e_40fd3b68-f3d3-4a2e-b47f-f4bdd245b8b3_1.4=4|Ht9Lm00LXEKsGA2Wp3FKqJZWcuzScZrk7eiDRKW4vDUqj5mmmHxulJM4bzKPtiZeHKBjv4VDzrZyvEMvZpW8nQ9YMywv5tkRMv+z+kEr2o0xDLpIcyn1I6DdwycGH5R2SLr0qKUdwc8+IrGksIZisTV04v3AGGvfwNwRMj206Xh1RI1gAD2sFuPPaWevQOaxaAXcDC0iLrvW9aAfPDhwPl7mhs1mcAJqnqBiwMkOKFtZrUIz7Fy1Vythx3BxTHwwdfxaW7ei/d4nphqzVQX+DUGIHh38SG8ALfvamdcrq3g=; expires=Sun, 01 Oct 2023 16:56:20 GMT; path=/; Secure; SameSite=None". Invalid 'expires' attribute: Sun, 01 Oct 2023 16:56:20 GMT
2023-10-01 18:46:23,743 ERROR [CaldavConnection-48954] davmail.exchange.ExchangeSession  - Exchange login exception: Not Found
2023-10-01 18:46:23,744 ERROR [CaldavConnection-48954] davmail  - Exchange login exception: Not Found
davmail.exception.DavMailException: Exchange login exception: Not Found
        at davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:239)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:208)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:93)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:178)
2023-10-01 18:46:24,784 INFO  [CaldavConnection-48954] davmail.connection  - DISCONNECT - 127.0.0.1:48954
2023-10-01 18:46:24,915 INFO  [davmail.caldav.CaldavServer] davmail.connection  - CONNECT - 127.0.0.1:48606
2023-10-01 18:46:25,918 WARN  [CaldavConnection-48606] org.apache.http.client.protocol.ResponseProcessCookies  - Invalid cookie header: "Set-Cookie: AzureAppProxyPreauthSessionCookie_56db8f93-efa4-406f-ab67-0221b97da76e_46f0d125-5967-463c-b3e0-d121ae638f7f_1.4=4|k19dI5NJyITyx33el+kVKuglkylWfsMXIYz/iDbF69z7Ur0Qn1n/9By41u7qgG54isEK+zqWjguZpXZMY9qxi215o2M190d1s0PXa+wX2SWBhzGdvwDmL2Iol8jDAvmk+Wjtz9FGp0WGS7V0yGNc28b78jvUHvYXQ6in2ONUcFV2csFwlqjd0sNCqEczVqPJLiZkXljZpl2RmbKOom9nuYYzIx0rj4NA3wZfMvIWTMEGHxHwMWFvjAdZoj/KAstL0JaKcWcSatTbBuIrj+D+pRlGfzZPDQDzs1iwHJblKak=; expires=Sun, 01 Oct 2023 16:56:25 GMT; path=/; Secure; SameSite=None". Invalid 'expires' attribute: Sun, 01 Oct 2023 16:56:25 GMT
2023-10-01 18:46:26,168 WARN  [CaldavConnection-48606] org.apache.http.client.protocol.ResponseProcessCookies  - Invalid cookie header: "Set-Cookie: AzureAppProxyPreauthSessionCookie_56db8f93-efa4-406f-ab67-0221b97da76e_d7327d47-4c0f-402b-a5c8-42e3a22434fa_1.4=4|ir07tKC93MuNzpDopWVe+X52RrKe2yL8zkNb5rO+c6iZ9zfaRg1zGPkpCToxnJWjFjoWjKF0SLx+RaBvP9Dm9s1dpdNy81VPk1UVVrw+R00ij9ldfmtyWjwwsFG0AzcxuhD3pLGVV3DNWMQRTD6mLPqqTmGW40nIP9rUJhdFnvOOigEtUCKvur6EVeCOcPZCSF0oprdFetg+ZwPTrSHNhFY4c8xgRhex/Zy7AZKohJtRuCzH5BWxWNqM/kO+r543mh00Tq6YFPw3VSWI3RLkI8ecwa/qvq4RK4ho3pyG9GA=; expires=Sun, 01 Oct 2023 16:56:26 GMT; path=/; Secure; SameSite=None". Invalid 'expires' attribute: Sun, 01 Oct 2023 16:56:26 GMT
2023-10-01 18:46:27,369 ERROR [CaldavConnection-48606] davmail.exchange.ExchangeSession  - Exchange login exception: Not Found
2023-10-01 18:46:27,369 ERROR [CaldavConnection-48606] davmail  - Exchange login exception: Not Found
davmail.exception.DavMailException: Exchange login exception: Not Found
        at davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:239)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:208)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:93)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:178)
2023-10-01 18:46:28,373 INFO  [CaldavConnection-48606] davmail.connection  - DISCONNECT - 127.0.0.1:48606
```
