### ISSUE TITLE
android davx notes sync error via jtx board

### ISSUE THREAD

**Issue by f1-outsourcing** [mguessan/davmail#303]
```
Aug 18 22:26:50 xxxxxxxxxx davmail: displayMessage - java.lang.NullPointerException
Aug 18 22:26:50 xxxxxxxxxx     at davmail.exchange.VCalendar.isTodo(VCalendar.java:765)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.exchange.ExchangeSession$Event.<init>(ExchangeSession.java:2042)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession$Event.<init>(EwsExchangeSession.java:1474)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2615)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:2658)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:299)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
Aug 18 22:26:50 xxxxxxxxxx     at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
Aug 18 22:34:18 xxxxxxxxxx davmail: displayMessage - java.lang.NullPointerException
Aug 18 22:34:18 xxxxxxxxxx     at davmail.exchange.VCalendar.isTodo(VCalendar.java:765)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.exchange.ExchangeSession$Event.<init>(ExchangeSession.java:2042)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession$Event.<init>(EwsExchangeSession.java:1474)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2615)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:2658)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:299)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
Aug 18 22:34:18 xxxxxxxxxx     at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
Aug 18 22:34:19 xxxxxxxxxx davmail: displayMessage - java.lang.NullPointerException
Aug 18 22:34:19 xxxxxxxxxx     at davmail.exchange.VCalendar.isTodo(VCalendar.java:765)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.exchange.ExchangeSession$Event.<init>(ExchangeSession.java:2042)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession$Event.<init>(EwsExchangeSession.java:1474)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2615)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:2658)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:299)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
Aug 18 22:34:19 xxxxxxxxxx     at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
```

**Comment by mguessan** [comment]
Events must be very broken if you get a nullpointer there: means no VEVENT in content.
Anyway I fixed the code to avoid this exception

**Comment by f1-outsourcing** [comment]
Thanks! Do you think you will publish a release any time soon?

**Comment by mguessan** [comment]
Reviewing old open tickets, this one was fixed and delivered a long time ago.

Closing ticket.
