### ISSUE TITLE
Can't send large attachments

### ISSUE THREAD

**Issue by DUOLabs333** [mguessan/davmail#307]
Sending a large attachment (a 35MB PDF) fails with `java.lang.OutOfMemoryError: Java heap space` after ~2 min delay. Stack trace:
```
Exception in thread SmtpConnection-44626 java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.codec.binary.BaseNCodec.resizeBuffer(BaseNCodec.java:254)
        at org.apache.commons.codec.binary.BaseNCodec.ensureBufferSize(BaseNCodec.java:270)
        at org.apache.commons.codec.binary.Base64.encode(Base64.java:381)
        at org.apache.commons.codec.binary.BaseNCodec.encode(BaseNCodec.java:452)
        at org.apache.commons.codec.binary.BaseNCodec.encode(BaseNCodec.java:431)
        at org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:678)
        at org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:641)
        at org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:622)
        at org.apache.commons.codec.binary.Base64.encodeBase64(Base64.java:555)
        at davmail.util.IOUtil.encodeBase64(IOUtil.java:109)
        at davmail.exchange.ews.EwsExchangeSession.sendMessage(EwsExchangeSession.java:451)
        at davmail.exchange.ews.EwsExchangeSession.sendMessage(EwsExchangeSession.java:480)
        at davmail.exchange.ExchangeSession.sendMessage(ExchangeSession.java:807)
        at davmail.smtp.SmtpConnection.run(SmtpConnection.java:167)
```

**Comment by mguessan** [comment]
I won't comment on the fact that it's a bad idea to send a 30MB PDF.

You can adjust DavMail maximum memory usage by changing -Xmx512M value, e.g. -Xmx2G
=> in davmail script wrapper on Linux
=> by providing a winrun4j davmail64.ini config file on windows:

```
ini.override=true
vm.location=./jre/bin/server/jvm.dll
vm.sysfirst=false

main.class=davmail.DavGateway
classpath.1=davmail.jar
classpath.2=lib/activation-1.1.1.jar
classpath.3=lib/commons-codec-1.11.jar
classpath.4=lib/commons-collections-3.1.jar
classpath.5=lib/commons-logging-1.0.4.jar
classpath.6=lib/htmlcleaner-2.21.jar
classpath.7=lib/httpclient-4.5.6.jar
classpath.8=lib/httpcore-4.4.10.jar
classpath.9=lib/jackrabbit-webdav-2.14.6.jar
classpath.10=lib/javax.mail-1.5.6.jar
classpath.11=lib/jcharset-2.0.jar
classpath.12=lib/jcifs-1.3.14.jar
classpath.13=lib/jdom-1.0.jar
classpath.14=lib/jettison-1.5.4.jar
classpath.15=lib/log4j-1.2.17.jar
classpath.16=lib/slf4j-api-1.7.25.jar
classpath.17=lib/slf4j-log4j12-1.7.25.jar
classpath.18=lib/stax-api-1.0.1.jar
classpath.19=lib/stax2-api-3.1.1.jar
classpath.20=lib/winrun4j-0.4.5.jar
classpath.21=lib/woodstox-core-6.4.0.jar

vm.version.min=1.8
vmarg.1=-Dsun.net.inetaddr.ttl=60
vmarg.2=-XmX2G
vmarg.3=--add-exports
vmarg.4=java.base/sun.net.www.protocol.https=ALL-UNNAMED

[ErrorMessages]
java.not.found=A suitable version of Java could not be found on your system, please install Java (64-bit) from http://java.com/en/download/manual.jsp
java.failed=Java failed to startup successfully, please install Java (64-bit) from http://java.com/en/download/manual.jsp
```
