### ISSUE TITLE
5.2 Stopped working on Ubuntu 18.04-derivative

### ISSUE THREAD

**Issue by stragu** [mguessan/davmail#31]
Hi there

(NB: I looked into #27 but it does not seem to be the same issue as me, I don't have a swt.jar file)

davmail (latest version, 5.2.0-2961-1) was working wonderfully for a couple of months on my laptop with ~Ubuntu Budgie 18.04. A few days ago, I noticed the tray icon wasn't showing up anymore, and my calendar wasn't syncing in Thunderbird. When I try to open davmail, it only shows the icon in my launcher and then disappears. No GUI or anything.

Executing `davmail` in the terminal gives me this, not sure if it helps:

```
Exception in thread "AWT-EventQueue-1" java.lang.UnsupportedClassVersionError: javafx/embed/swing/JFXPanel has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at davmail.ui.SettingsFrame.isJavaFXAvailable(SettingsFrame.java:267)
	at davmail.ui.SettingsFrame.getSettingsPanel(SettingsFrame.java:164)
	at davmail.ui.SettingsFrame.<init>(SettingsFrame.java:748)
	at davmail.ui.tray.AwtGatewayTray.createAndShowGUI(AwtGatewayTray.java:235)
	at davmail.ui.tray.AwtGatewayTray$7.run(AwtGatewayTray.java:187)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

I am not sure what initiated the issue, I regularly update my system but I don't use the calendar that often so didn't notice it straight away.

Any idea how I could troubleshoot that?

**Comment by mguessan** [comment]
You probably have an updated OpenJFX 11 with an older OpenJDK8
=> you can try to upgrade your JDK

**Comment by stragu** [comment]
Thanks @mguessan , you put me on the right track.

`java -version` showed me that I was using `java-1.8.0-openjdk-amd64`.

To install openjdk version 11, I run:

`sudo apt install default-jdk`

And could then see the two version installed with:

`sudo update-java-alternatives --list`

And could finally change the version in use with:

`sudo update-java-alternatives --set java-1.11.0-openjdk-amd64`

I can now run davmail! Thanks heaps :)
