### ISSUE TITLE
Allow tenant id configuration for oauth2

### ISSUE THREAD

**Issue by thuck** [mguessan/davmail#32]
Looks like to make the O365Modern to work I need to pass the tenant id when doing the authorization and when getting the token.
```diff --git a/src/java/davmail/exchange/auth/O365Authenticator.java b/src/java/davmail/exchange/auth/O365Authenticator.java
index d71ee714..dacddd2a 100644
--- a/src/java/davmail/exchange/auth/O365Authenticator.java
+++ b/src/java/davmail/exchange/auth/O365Authenticator.java
@@ -78,8 +78,12 @@ public class O365Authenticator implements ExchangeAuthenticator {
             String clientId = Settings.getProperty("davmail.oauth.clientId", "facd6cff-a294-4415-b59f-c5b01937d7bd");
             // standard native app redirectUri
             String redirectUri = Settings.getProperty("davmail.oauth.redirectUri", "https://login.microsoftonline.com/common/oauth2/nativeclient");
+            // tenant id^M
+            String tenantId = Settings.getProperty("davmail.oauth.tenantId", "common");^M
 
-            String url = "https://login.microsoftonline.com/common/oauth2/authorize"
+            String url = "https://login.microsoftonline.com/"^M
+                    + tenantId^M
+                    +"/oauth2/authorize"^M
                     + "?client_id=" + clientId
                     + "&response_type=code"
                     + "&redirect_uri=" + redirectUri
diff --git a/src/java/davmail/exchange/auth/O365Token.java b/src/java/davmail/exchange/auth/O365Token.java
index 239cf364..23954eed 100644
--- a/src/java/davmail/exchange/auth/O365Token.java
+++ b/src/java/davmail/exchange/auth/O365Token.java
@@ -33,7 +33,8 @@ import java.io.IOException;
 import java.util.Date;
 
 public class O365Token {
-    protected final String TOKEN_URL = "https://login.microsoftonline.com/common/oauth2/token";
+    String tenantId = Settings.getProperty("davmail.oauth.tenantId", "common");^M
+    protected final String TOKEN_URL = "https://login.microsoftonline.com/"+tenantId+"/oauth2/token";^M
     protected final String RESOURCE_URL = "https://outlook.office365.com/";
 
     protected static final Logger LOGGER = Logger.getLogger(O365Token.class);
```
I'm trying to test this, but for some reason it doesn't matter if I compile with my change or without it I always get the error below:
```2019-05-06 14:09:53,653 DEBUG [ImapConnection-34130] davmail.exchange.ExchangeSession  - java.lang.ClassNotFoundException: davmail.exchange.auth.O365InteractiveAuthenticator
java.lang.ClassNotFoundException: davmail.exchange.auth.O365InteractiveAuthenticator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:172)
        at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
        at davmail.imap.ImapConnection.run(ImapConnection.java:112)
```

**Comment by mguessan** [comment]
Java world recently became very tricky, thanks to Oracle mess...

Anyway, we now check that OpenJFX is available at compile time. If not interactive authenticators are not available in compiled packages.

On windows (and maybe OSX, not tested), a good alternative to broken Oracle JDKs seems to be Azul with ZuluFX, please check:
https://www.azul.com/downloads/zulu/zulufx/

On Linux latest OpenJDK with OpenJFX should be OK.

**Comment by thuck** [comment]
@mguessan yep; using the zulufx it compiles with the interactive.
But looks like there is some regression on the O365Interactive; using the 5.2.0 I can connect; but using the master it fails. I need to do some bisect later to see where is this failing.
Let me test the tenant id on the version that works, just be sure if I need to change something else.

**Comment by thuck** [comment]
@mguessan i finished the bisect and looks like this commit makes the auth to stop to work:
```git bisect good                                                                                                                                                                                                                             5.4s
6553fe02edcc9d5c64c7725ec8a653d5f661cd2e is the first bad commit
commit 6553fe02edcc9d5c64c7725ec8a653d5f661cd2e
Author: Mickaël Guessant <mguessan@free.fr>
Date:   Sat Feb 23 17:55:56 2019 +0000

    EWS: fix support for new Okta authentication form, need to disable integrity check
    
    git-svn-id: https://svn.code.sf.net/p/davmail/code/trunk@2977 3d1905a2-6b24-0410-a738-b14d5a86fcbd

:040000 040000 b05cf7afe9a906890a63ea26f0975edcff3c4fec 286c2947b0f3db4545249c5495d729829a4e27cd M      src
```

**Comment by thuck** [comment]
The problem is this:
httpsURLConnection.setRequestProperty("User-Agent", DavGatewayHttpClientFacade.getUserAgent());

Looks like the remote doesn't like the default user agent:
public static final String IE_USER_AGENT = "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)";

If I configure the user agent to  firefox it works:
davmail.userAgent=Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0

**Comment by mguessan** [comment]
Ok, overriding user agent in webview was a bad idea => removed in trunk.

**Comment by mguessan** [comment]
Also implemented a new setting for tenantId override, thanks for your contribution.

**Comment by mguessan** [comment]
Closing issue.
