### ISSUE TITLE
Javax.mail casting errors

### ISSUE THREAD

**Issue by chriskanan** [mguessan/davmail#339]
I'm getting some errors, which seem to be related to javax.mail and casting with an imap setup. 

```
591 ERROR [ImapConnection] davmail  - class javax.mail.util.SharedByteArrayInputStream cannot be cast to class javax.mail.internet.MimeMessage (javax.mail.util.SharedByteArrayInputStream and javax.mail.internet.MimeMessage are in unnamed module of loader 'app')
java.lang.ClassCastException: class javax.mail.util.SharedByteArrayInputStream cannot be cast to class javax.mail.internet.MimeMessage (javax.mail.util.SharedByteArrayInputStream and javax.mail.internet.MimeMessage are in unnamed module of loader 'app')
        at davmail.imap.ImapConnection.appendBodyStructure(ImapConnection.java:1404)
        at davmail.imap.ImapConnection.appendBodyStructure(ImapConnection.java:1304)
        at davmail.imap.ImapConnection.appendBodyStructure(ImapConnection.java:1281)
        at davmail.imap.ImapConnection.handleFetch(ImapConnection.java:894)
        at davmail.imap.ImapConnection.run(ImapConnection.java:332)

308 ERROR [ImapConnection-49752] davmail  - class javax.mail.util.SharedByteArrayInputStream cannot be cast to class javax.mail.internet.MimeMessage (javax.mail.util.SharedByteArrayInputStream and javax.mail.internet.MimeMessage are in unnamed module of loader 'app')
java.lang.ClassCastException: class javax.mail.util.SharedByteArrayInputStream cannot be cast to class javax.mail.internet.MimeMessage (javax.mail.util.SharedByteArrayInputStream and javax.mail.internet.MimeMessage are in unnamed module of loader 'app')
```

**Comment by mguessan** [comment]
Probably a malformed message, adding a failover case to avoid exception
