### ISSUE TITLE
Thunderbird  user cant send Meeting request to Exchange users

### ISSUE THREAD

**Issue by tceydeliler** [mguessan/davmail#358]
Hi, 
I set an meeting request in TB to send exchange users but they cand get  this meeting requests. What should I do?
Here is davmail log:
```
2024-06-05 09:54:25,163 ERROR [CaldavConnection-33196] davmail  - Can't find resource for bundle java.util.PropertyResourceBundle, key +030000
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key +030000
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at davmail.exchange.VCalendar.fixTimezoneToServer(VCalendar.java:396)
	at davmail.exchange.VCalendar.fixVCalendar(VCalendar.java:206)
	at davmail.exchange.ExchangeSession$Event.fixICS(ExchangeSession.java:2150)
	at davmail.exchange.ExchangeSession$Event.<init>(ExchangeSession.java:2040)
	at davmail.exchange.ews.EwsExchangeSession$Event.<init>(EwsExchangeSession.java:1474)
	at davmail.exchange.ews.EwsExchangeSession.internalCreateOrUpdateEvent(EwsExchangeSession.java:2615)
	at davmail.exchange.ExchangeSession.createOrUpdateItem(ExchangeSession.java:2658)
	at davmail.caldav.CaldavConnection.handleFolderOrItem(CaldavConnection.java:299)
	at davmail.caldav.CaldavConnection.handleRequest(CaldavConnection.java:237)
	at davmail.caldav.CaldavConnection.run(CaldavConnection.java:180)
```

**Comment by mguessan** [comment]
This was fixed a while ago, see:
https://github.com/mguessan/davmail/issues/309

Please make sure you use the latest DavMail version

**Comment by mguessan** [comment]
Closing issue
