### ISSUE TITLE
Authenticated username does not match the provided

### ISSUE THREAD

**Issue by Ingvix** [mguessan/davmail#367]
I trying to set up davmail for my personal mail. With davmail's own clientId I get the same notice as https://github.com/mguessan/davmail/issues/363#issue-2409484136
I then tried the Outlook Desktop clientId and redirectUri and was able proceed to sign in. After pasting the code I get this error:
```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Authenticated username live.com#<my.email>@hotmail.com does not match <my.email>@hotmail.com
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
        at davmail.BundleMessage.format(BundleMessage.java:152)
        at davmail.BundleMessage.format(BundleMessage.java:69)
        at davmail.exception.DavMailException.getMessage(DavMailException.java:59)
        at davmail.BundleMessage.getExceptionMessage(BundleMessage.java:204)
        at davmail.BundleMessage.getExceptionLogMessage(BundleMessage.java:176)
        at davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
        at davmail.ui.tray.DavGatewayTray.error(DavGatewayTray.java:194)
        at davmail.imap.ImapConnection.run(ImapConnection.java:161)
```
I suppose it could be due to davmail not understanding the newer API that Outlook has been updated to handle?

**Comment by ttesty** [comment]
Bug in the code...  .... username = tokenBody.getString("unique_name") .. without parsing past the # in the value of "unique_name" key.

Token: {"aud":"d3590ed6-52b3-4102-aeff-aad2292ab01c","iss":"https://sts.windows.net/3ceb7ded-6237-4abf-aed0-f741fb55330a/","iat":X,"nbf":X,"exp":X,"altsecid":"1:live.com:X","amr":["pwd"],"email":"[person@live.com](mailto:person@live.com)","family_name":"X","given_name":"X","idp":"live.com","idtyp":"user","ipaddr":"X","name":"X","oid":"X","puid":"X","rh":"","sub":"","tid":"X","unique_name":"live.com#[person@live.com](mailto:person@live.com)","ver":"1.0","xms_idrel":"4 1"}

.... username = tokenBody.getString("unique_name");
?

You could check "email" field too... or parse on unique_name... past #


=========================
      token = O365Token.build(tenantId, clientId, redirectUri, code, password);
    LOGGER.debug("Authenticated username: " + token.getUsername());
    if (username != null && !username.isEmpty() && !username.equalsIgnoreCase(token.getUsername())) {
        throw new DavMailAuthenticationException("Authenticated username " + token.getUsername() + " does not match " + username);
    }

// get username from id_token
String idToken = jsonToken.optString("id_token");
if (idToken != null && idToken.contains(".")) {
String decodedJwt = IOUtil.decodeBase64AsString(idToken.substring(idToken.indexOf("."), idToken.lastIndexOf(".")));
try {
JSONObject tokenBody = new JSONObject(decodedJwt);
LOGGER.debug("Token: " + tokenBody);
username = tokenBody.getString("unique_name");
} catch (JSONException e) {
LOGGER.warn("Invalid id_token " + e.getMessage(), e);
}
}

**Comment by ttesty** [comment]
Once you solve this problem, there's another right after about bad authentication.

**Comment by mguessan** [comment]
This is related to #393, username matching is fixed in trunk, however this is not enough to make DavMail work with live.com/outlook.com accounts.

So far we haven't found if there is a way to authenticate with personal account and access mailbox over EWS.

Closing this ticket for now, tracking updates in the other one

**Comment by jolars** [comment]
I am still running to a similar problem:

```
IMAP command 'LOGIN <user> <pass>' returned an error: unable to handle request: Can't find resource for bundle java.util.PropertyResourceBundle, key Authenticated username <work-login-in> does not match <work-email-id>
```

when using `O365Manual` and the outlook client id redirect uri trick. I am able to find the `urn: url` and copy-paste it into davmail, but then I run into this error. It doesnt seem like this is related to #393, but maybe I'm wrong?

**Comment by mguessan** [comment]
@jolars if you are trying to connect to a live.com account this will not work with Outlook desktop clientId with the urn: redirectUri.

In fact at the moment live.com accounts are not supported, currently working on a graph API backend that may work.

**Comment by jolars** [comment]
> @jolars if you are trying to connect to a live.com account this will not work with Outlook desktop clientId with the urn: redirectUri.
>
> In fact at the moment live.com accounts are not supported, currently working on a graph API backend that may work.

Thanks, but no, I am using Outlook365 through my work e-mail. It seems like I am receiving a token correctly but that it's associated with the wrong user name.

I look forward to the work on the Graph backend. Hopefully that will help resolve many of these issues.
