### ISSUE TITLE
Request for Enhanced Debugging Information (davmail.exception.DavMailException: Exchange login exception: Received fatal alert: handshake_failure)

### ISSUE THREAD

**Issue by ifrh** [mguessan/davmail#374]
Hi there,

I had tried to use DavMail (Current version: 6.2.2-3546)  
https://sourceforge.net/projects/davmail/files/davmail/6.2.2/davmail-6.2.2-3546-windows-standalone.zip/download
as Gateway to an Exchange Server so that Thunderbird 115.16.3 (32-Bit) and Thunderbird 128.5.1esr (64-Bit)
can access to personal or shared calendars. But the handshake failed without more information.
=> Just to mention TB can get access to the personal calender via "TbSync" and "EAS-4-TBsync".

But I want to get access to the shared calendars as well, which is out of scope of "EAS-4-TBsync".

Sadly DavMail throws an Java Exception and did not connect to the Exchange Server.
```

Category:	davmail.exchange.ExchangeSession
Message:		OWA authentication in EWS mode
Location:	davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:194)

Category:	davmail.http.DavGatewaySSLSocketFactory
Message:		createSocket <OWA-Server> 443
Location:	davmail.http.DavGatewaySSLSocketFactory.createSocket(DavGatewaySSLSocketFactory.java:184)

Category:	davmail.http.HttpClientAdapter
Message:		Creating NTCredentials for user <personal-email> workstation <pc-name> domain <empty> 
Location:	davmail.http.HttpClientAdapter.setCredentials(HttpClientAdapter.java:598)

Category:	davmail.http.HttpClientAdapter
Message:		GET <OWA-Website>
Location:	davmail.http.HttpClientAdapter.executeFollowRedirect(HttpClientAdapter.java:445)

Category:	davmail.http.DavGatewaySSLSocketFactory
Message:		createSocket <OWA-Server> 443
Location:	davmail.http.DavGatewaySSLSocketFactory.createSocket(DavGatewaySSLSocketFactory.java:184)

Category:	davmail.exchange.ExchangeSession
Message:		Exchange login exception: Received fatal alert: handshake_failure
Location:	davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:237)

Category:	davmail
Message:		Exchange login exception: Received fatal alert: handshake_failure
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
Thrown:
davmail.exception.DavMailException: Exchange login exception: Received fatal alert: handshake_failure
	at davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:238)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:199)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
	at davmail.caldav.CaldavConnection.run(CaldavConnection.java:178)
```

```
Thread:        CaldavConnection-49929
Message #:    450
Level:        ERROR
NDC:
Category:    davmail
Message:        Exchange login exception: Received fatal alert: handshake_failure
Location: davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:117)
Thrown:
davmail.exception.DavMailException: Exchange login exception: Received fatal alert: handshake_failure
    at davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:238)
    at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:199)
    at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
    at davmail.caldav.CaldavConnection.run(CaldavConnection.java:178) 
```

**Request for Enhanced Debugging Information**

Since there are problems with handshakes and I would like to gather more detailed information. 
It would be nice to add the following information to logging output:

    Protocol version details:
        What specific security protocol version(s) were attempted during the handshake?
        Which fallbacks to older protocol versions had been tried?

    Certificate information:
        Which certificates were presented by the client/server?
        Were there any issues with certificate validation?

    Cipher suite details:
        What cipher suites were offered and accepted?
        Were there any cipher suite mismatches?

    Key exchange and authentication methods:
        What key exchange algorithms were used?
        Were there any issues with client authentication?

    Detailed handshake logs:
        Enable verbose logging of the entire SSL/TLS handshake process.
        Include any error messages or warnings generated during the handshake.

**Comment by esabol** [comment]
Are you aware of the WIRE debug mode, @ifrh ? Check the first FAQ here:

https://davmail.sourceforge.net/faq.html#Feedback

Edit your `~/.davmail.properties` file and add the following lines to the file:
```
log4j.logger.httpclient.wire=DEBUG
log4j.logger.org.apache.http.wire=DEBUG
```
Quit and restart the DavMail application. DavMail will then create a detailed log of what it is doing. This log will be stored in a davmail.log file. By default, it will be located in DavMail's current working directory on Linux and Windows. Note that this log file might include authentication information like your password and other account details that you should not share online. I hope this helps!

**Comment by ifrh** [comment]
> Are you aware of the WIRE debug mode, @ifrh ? Check the first FAQ here:
> 
> https://davmail.sourceforge.net/faq.html#Feedback

Thanks for pointer, but did not help.

> 
> Edit your `~/.davmail.properties` file and add the following lines to the file:
> 

Well in Windows I did not find any file named `.davmail.properties`. 
So I had created one

![grafik](https://github.com/user-attachments/assets/8c953929-f8cf-4abd-a057-e31ebb8e9efe)


> ```
> log4j.logger.httpclient.wire=DEBUG
> log4j.logger.org.apache.http.wire=DEBUG
> ```

having that above content.


> 
> Quit and restart the DavMail application. DavMail will then create a detailed log of what it is doing. This log will be stored in a davmail.log file. By default, it will be located in DavMail's current working directory on Linux and Windows. 

No log file had been created, and the output to the Window _LogFactor5_ seems to be the same, as without that fresh created properties-file.

![grafik](https://github.com/user-attachments/assets/65ea8509-0f3d-432a-92e3-e15b07ca3bde)


![grafik](https://github.com/user-attachments/assets/04535790-0c7e-4de3-af66-9f3f2d04bad0)

**Comment by ifrh** [comment]
> > Quit and restart the DavMail application. DavMail will then create a detailed log of what it is doing. This log will be stored in a davmail.log file. By default, it will be located in DavMail's current working directory on Linux and Windows.
> 
> No log file had been created, and the output to the Window _LogFactor5_ seems to be the same, as without that fresh created properties-file.
> 

Well, I'll have to change the path location 
![grafik](https://github.com/user-attachments/assets/4eec8731-ffa3-43d2-bdf2-37ccaec5a17c)

and than have a look again.

**Comment by ifrh** [comment]
Using Firefox to access the OWA-Landingpage is using TLS 1.3
![grafik](https://github.com/user-attachments/assets/5901fa15-fdf7-4228-bcd9-c35fedb96a10)

**Comment by ifrh** [comment]
Okay it seems to me, that MailDav do not support TSL 1.3 :

````
2024-12-04 23:13:48,607 DEBUG [CaldavConnection-54261] org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
[...]
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.client.protocol.RequestAddCookies  - CookieSpec selected: default
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.client.protocol.RequestAuthCache  - Auth cache not set in the context
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection request: [route: {s}->https://OWA-SERVER.DOMAIN.TLD:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection leased: [id: 1][route: {s}->https://OWA-SERVER.DOMAIN.TLD:443][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 20]
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.impl.execchain.MainClientExec  - Opening connection {s}->https://OWA-SERVER.DOMAIN.TLD:443
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.DefaultHttpClientConnectionOperator  - Connecting to OWA-SERVER.DOMAIN.TLD/SOME-IP-ADDRESS:443
2024-12-04 23:13:48,752 DEBUG [CaldavConnection-54261] org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Connecting socket to OWA-SERVER.DOMAIN.TLD/SOME-IP-ADDRESS:443 with timeout 10000
2024-12-04 23:13:48,814 DEBUG [CaldavConnection-54261] davmail.http.DavGatewaySSLSocketFactory  - createSocket OWA-SERVER.DOMAIN.TLD 443
2024-12-04 23:13:48,814 DEBUG [CaldavConnection-54261] org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]
2024-12-04 23:13:48,824 DEBUG [CaldavConnection-54261] org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Enabled cipher suites:[TLS_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256, TLS_CHACHA20_POLY1305_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
2024-12-04 23:13:48,824 DEBUG [CaldavConnection-54261] org.apache.http.conn.ssl.SSLConnectionSocketFactory  - Starting handshake
2024-12-04 23:13:48,897 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.DefaultManagedHttpClientConnection  - http-outgoing-2: Shutdown connection
2024-12-04 23:13:48,948 DEBUG [CaldavConnection-54261] org.apache.http.impl.execchain.MainClientExec  - Connection discarded
2024-12-04 23:13:48,948 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection released: [id: 1][route: {s}->https://OWA-SERVER.DOMAIN.TLD:443][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 20]
2024-12-04 23:13:48,948 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection manager is shutting down
2024-12-04 23:13:48,957 DEBUG [CaldavConnection-54261] org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection manager shut down
2024-12-04 23:13:48,957 ERROR [CaldavConnection-54261] davmail.exchange.ExchangeSession  - Exchange login exception: Received fatal alert: handshake_failure
2024-12-04 23:13:48,969 ERROR [CaldavConnection-54261] davmail  - Exchange login exception: Received fatal alert: handshake_failure
davmail.exception.DavMailException: Exchange login exception: Received fatal alert: handshake_failure
	at davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:238)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:208)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
	at davmail.caldav.CaldavConnection.run(CaldavConnection.java:178)

```

**Comment by ifrh** [comment]
I close this issue, because discussion in issue https://github.com/mguessan/davmail/issues/375 solved the _handshake failure_ problem.
