### ISSUE TITLE
SSL failures with macOS

### ISSUE THREAD

**Issue by rossburton** [mguessan/davmail#50]
If I try to connect to my OWA server I get SSL failures:
```
$ nc localhost 1025
421 DavMail configuration exception:
Connect exception: javax.net.ssl.SSLHandshakeException Remote host terminated the handshake
```

Adding the debug flag shows this logging:
```
javax.net.ssl|DEBUG|19|SmtpConnection-57369|2019-07-30 24:16:14.408 BST|SSLCipher.java:463|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472




javax.net.ssl|ERROR|19|SmtpConnection-57369|2019-07-30 24:17:29.712 BST|TransportContext.java:312|Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
  	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1349)
  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1188)
  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
  	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:721)
  	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:998)
  	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
  	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
  	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
  	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
  	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
  	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
  	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
  	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
  	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
  	at davmail.http.DavGatewayHttpClientFacade.executeTestMethod(DavGatewayHttpClientFacade.java:694)
  	at davmail.exchange.ExchangeSessionFactory.checkConfig(ExchangeSessionFactory.java:278)
  	at davmail.smtp.SmtpConnection.run(SmtpConnection.java:65)
  Caused by: java.io.EOFException: SSL peer shut down incorrectly
  	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
  	... 16 more}
```

Latest macOS Mojave 10.14.6, with Oracle Java 12.0.2 2019-07-16.

**Comment by mguessan** [comment]
Definitely related to SSL settings. Possible cause: you have a very recent JDK and an older Exchange with incompatible SSL/TLS settings.
=> I would try with an Oracle JDK 8 or Zulu JDK 8:
https://www.azul.com/downloads/zulu-community/

**Comment by mguessan** [comment]
Not a DavMail issue
