### ISSUE TITLE
Exception closing client output stream Socket closed

### ISSUE THREAD

**Issue by Djiko** [mguessan/davmail#56]
The error "Exception closing client output stream Socket closed" happens when closing my email client (Thunderbird). It happens on DavMail 5.3.1-3079 but also happened on the previous version. This has no real impact (no lost data, client app is closing normallly).

`Date:			Tue Sep 10 17:02:01 CEST 2019 (1568127721702)
Thread:		ImapConnection-51108
Message #:	52
Level:		DEBUG
NDC:			
Category:	davmail
Message:		Exception closing client output stream Socket closed
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:114)
Thrown:
java.net.SocketException: Socket closed
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at davmail.AbstractConnection.close(AbstractConnection.java:262)
	at davmail.imap.ImapConnection.run(ImapConnection.java:681)`

**Comment by mguessan** [comment]
Indeed, this is not a real error => removed those log messages.
