### ISSUE TITLE
AWS Workmail: NullPointerException trying to fetch mails

### ISSUE THREAD

**Issue by tobiasgraf** [mguessan/davmail#97]
Hi,

we recently switched to AWS Workmail and I tried using DavMail.
EWS url: `https://ews.mail.eu-west-1.awsapps.com/EWS/Exchange.asmx`
ports and everything else on default

I'm using 5.4.0-trunk, but also tried 5.3.1 with the same error.
As client i'm using Thunderbird 68.6.0 (64-bit) on Linux Mint 19.3

When I try to fetch my mails I always get this NullPointerException

Anything I'm doing wrong or could try to resolve the issue?

(i removed some personal info from the log, username and email address)
```
2020-03-31 14:11:47,475 DEBUG [main] davmail.DavGateway  - Start DavMail in GUI mode
2020-03-31 14:11:48,164 DEBUG [main] davmail  - OS Name: Linux Java version: 11.0.6 64 System tray supported Current Desktop: X-Cinnamon
2020-03-31 14:11:48,193 INFO  [main] davmail  - SWT not available, using native system tray support
2020-03-31 14:11:48,385 INFO  [main] davmail  - DavMail Gateway 5.4.0-trunk listening on SMTP port 1025 POP port 1110 IMAP port 1143 CALDAV port 1080 LDAP port 1389 
2020-03-31 14:11:48,491 DEBUG [CheckRelease] davmail.http.HttpClientAdapter  - GET http://davmail.sourceforge.net/version.txt
2020-03-31 14:11:48,922 DEBUG [CheckRelease] davmail.DavGateway  - DavMail released version: 5.4.0-3135
2020-03-31 14:11:57,957 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
2020-03-31 14:11:57,989 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:46424 
2020-03-31 14:11:58,695 DEBUG [ImapConnection-46424] davmail.exchange.ExchangeSession  - Test configuration status: 401
2020-03-31 14:11:58,697 DEBUG [ImapConnection-46424] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 5.4.0-trunk server ready
2020-03-31 14:11:58,702 DEBUG [ImapConnection-46424] davmail  - < 1 authenticate LOGIN
2020-03-31 14:11:58,711 DEBUG [ImapConnection-46424] davmail  - > + <removed>
2020-03-31 14:11:58,713 DEBUG [ImapConnection-46424] davmail  - < <removed>
2020-03-31 14:11:58,714 DEBUG [ImapConnection-46424] davmail  - > + <removed>
2020-03-31 14:11:58,715 DEBUG [ImapConnection-46424] davmail  - < ********
2020-03-31 14:11:58,716 DEBUG [ImapConnection-46424] davmail.exchange.ExchangeSession  - Direct EWS authentication
2020-03-31 14:12:01,564 DEBUG [ImapConnection-46424] davmail.exchange.ExchangeSession  - Current user email is <myemail@address.com>, alias is <username?> on Exchange2010_SP1
2020-03-31 14:12:01,565 DEBUG [ImapConnection-46424] davmail.exchange.ExchangeSession  - Created new session davmail.exchange.ews.EwsExchangeSession@436d56ea for user <myemail@address.com>
2020-03-31 14:12:01,565 INFO  [ImapConnection-46424] davmail.connection  - LOGON - 127.0.0.1:46424 <myemail@address.com>
2020-03-31 14:12:01,566 DEBUG [ImapConnection-46424] davmail  - > 1 OK Authenticated
2020-03-31 14:12:01,568 DEBUG [ImapConnection-46424] davmail  - < 2 select "INBOX"
2020-03-31 14:12:01,959 DEBUG [ImapConnection-46424] davmail.imap.ImapConnection  - *
2020-03-31 14:12:03,388 DEBUG [ImapConnection-46424-LoadFolder] davmail  - Downloaded 131 KBytes from /ews/exchange.asmx
2020-03-31 14:12:03,457 DEBUG [ImapConnection-46424-LoadFolder] davmail  - Downloaded 263 KBytes from /ews/exchange.asmx
2020-03-31 14:12:03,527 DEBUG [ImapConnection-46424-LoadFolder] davmail  - Downloaded 395 KBytes from /ews/exchange.asmx
2020-03-31 14:12:03,599 DEBUG [ImapConnection-46424-LoadFolder] davmail  - Downloaded 527 KBytes from /ews/exchange.asmx
2020-03-31 14:12:03,673 DEBUG [ImapConnection-46424-LoadFolder] davmail  - Downloaded 655 KBytes from /ews/exchange.asmx
2020-03-31 14:12:03,676 DEBUG [ImapConnection-46424] davmail.exchange.FolderLoadThread  - Still loading INBOX (7040 messages)
2020-03-31 14:12:03,677 DEBUG [ImapConnection-46424] davmail  - >  7040 EXISTS
2020-03-31 14:12:03,677 DEBUG [ImapConnection-46424] davmail  - > * 12 RECENT
2020-03-31 14:12:03,678 DEBUG [ImapConnection-46424] davmail  - > * OK [UIDVALIDITY 1]
2020-03-31 14:12:03,678 DEBUG [ImapConnection-46424] davmail  - > * OK [UIDNEXT 0]
2020-03-31 14:12:03,678 DEBUG [ImapConnection-46424] davmail  - > * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk)
2020-03-31 14:12:03,679 DEBUG [ImapConnection-46424] davmail  - > * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk \*)]
2020-03-31 14:12:03,679 DEBUG [ImapConnection-46424] davmail  - > 2 OK [READ-WRITE] select completed
2020-03-31 14:12:03,721 DEBUG [ImapConnection-46424] davmail  - < 3 UID fetch 1:* (FLAGS)
2020-03-31 14:12:03,886 ERROR [ImapConnection-46424] davmail  - java.lang.NullPointerException
java.lang.NullPointerException
	at davmail.imap.ImapConnection$UIDRangeIterator.hasNextIndex(ImapConnection.java:1918)
	at davmail.imap.ImapConnection$UIDRangeIterator.hasNextInRange(ImapConnection.java:1914)
	at davmail.imap.ImapConnection$UIDRangeIterator.hasNext(ImapConnection.java:1926)
	at davmail.imap.ImapConnection.run(ImapConnection.java:312)
2020-03-31 14:12:03,888 DEBUG [ImapConnection-46424] davmail  - > 3 BAD unable to handle request: java.lang.NullPointerException
2020-03-31 14:12:03,889 INFO  [ImapConnection-46424] davmail.connection  - DISCONNECT - 127.0.0.1:46424 
```

**Comment by mguessan** [comment]
Ok, there must be something very wrong during loadMessages call
=> updated trunk to try to get more details, build will be available in a few seconds

**Comment by tobiasgraf** [comment]
Hi, Thanks for your reply.

I downloaded the new trunk version, here's the log

```
2020-04-01 11:05:57,692 DEBUG [main] davmail.DavGateway  - Start DavMail in GUI mode
2020-04-01 11:05:58,384 DEBUG [main] davmail  - OS Name: Linux Java version: 11.0.6 64 System tray supported Current Desktop: X-Cinnamon
2020-04-01 11:05:58,420 INFO  [main] davmail  - SWT not available, using native system tray support
2020-04-01 11:05:58,611 INFO  [main] davmail  - DavMail Gateway 5.4.0-trunk listening on SMTP port 1025 POP port 1110 IMAP port 1143 CALDAV port 1080 LDAP port 1389 
2020-04-01 11:05:58,962 DEBUG [CheckRelease] davmail.http.HttpClientAdapter  - GET http://davmail.sourceforge.net/version.txt
2020-04-01 11:05:59,365 DEBUG [CheckRelease] davmail.DavGateway  - DavMail released version: 5.4.0-3135
2020-04-01 11:06:17,863 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
2020-04-01 11:06:17,889 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:50098 
2020-04-01 11:06:18,679 DEBUG [ImapConnection-50098] davmail.exchange.ExchangeSession  - Test configuration status: 401
2020-04-01 11:06:18,681 DEBUG [ImapConnection-50098] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 5.4.0-trunk server ready
2020-04-01 11:06:18,684 DEBUG [ImapConnection-50098] davmail  - < 1 authenticate LOGIN
2020-04-01 11:06:18,695 DEBUG [ImapConnection-50098] davmail  - > + ************
2020-04-01 11:06:18,696 DEBUG [ImapConnection-50098] davmail  - < ********==
2020-04-01 11:06:18,696 DEBUG [ImapConnection-50098] davmail  - > + ******
2020-04-01 11:06:18,697 DEBUG [ImapConnection-50098] davmail  - < ********
2020-04-01 11:06:18,699 DEBUG [ImapConnection-50098] davmail.exchange.ExchangeSession  - Direct EWS authentication
2020-04-01 11:06:21,643 DEBUG [ImapConnection-50098] davmail.exchange.ExchangeSession  - Current user email is <email@address>, alias is tobias on Exchange2010_SP1
2020-04-01 11:06:21,644 DEBUG [ImapConnection-50098] davmail.exchange.ExchangeSession  - Created new session davmail.exchange.ews.EwsExchangeSession@2aef998 for user <email@address>
2020-04-01 11:06:21,644 INFO  [ImapConnection-50098] davmail.connection  - LOGON - 127.0.0.1:50098 <email@address>
2020-04-01 11:06:21,644 DEBUG [ImapConnection-50098] davmail  - > 1 OK Authenticated
2020-04-01 11:06:21,646 DEBUG [ImapConnection-50098] davmail  - < 2 select "INBOX"
2020-04-01 11:06:21,989 DEBUG [ImapConnection-50098] davmail.imap.ImapConnection  - *
2020-04-01 11:06:23,142 DEBUG [ImapConnection-50098-LoadFolder] davmail  - Downloaded 131 KBytes from /ews/exchange.asmx
2020-04-01 11:06:23,207 DEBUG [ImapConnection-50098-LoadFolder] davmail  - Downloaded 263 KBytes from /ews/exchange.asmx
2020-04-01 11:06:23,276 DEBUG [ImapConnection-50098-LoadFolder] davmail  - Downloaded 395 KBytes from /ews/exchange.asmx
2020-04-01 11:06:23,347 DEBUG [ImapConnection-50098-LoadFolder] davmail  - Downloaded 527 KBytes from /ews/exchange.asmx
2020-04-01 11:06:23,422 DEBUG [ImapConnection-50098-LoadFolder] davmail  - Downloaded 655 KBytes from /ews/exchange.asmx
2020-04-01 11:06:23,426 ERROR [ImapConnection-50098-LoadFolder] davmail.exchange.FolderLoadThread  - java.lang.NumberFormatException: null null
java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:758)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:680)
	at davmail.exchange.ews.EwsExchangeSession.searchMessages(EwsExchangeSession.java:664)
	at davmail.exchange.ExchangeSession.searchMessages(ExchangeSession.java:314)
	at davmail.exchange.ExchangeSession$Folder.loadMessages(ExchangeSession.java:1184)
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:46)
2020-04-01 11:06:23,429 DEBUG [ImapConnection-50098] davmail.exchange.FolderLoadThread  - Still loading INBOX (7045 messages)
2020-04-01 11:06:23,429 ERROR [ImapConnection-50098] davmail  - null
java.io.IOException: null
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:51)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:758)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:680)
	at davmail.exchange.ews.EwsExchangeSession.searchMessages(EwsExchangeSession.java:664)
	at davmail.exchange.ExchangeSession.searchMessages(ExchangeSession.java:314)
	at davmail.exchange.ExchangeSession$Folder.loadMessages(ExchangeSession.java:1184)
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:46)
2020-04-01 11:06:23,431 DEBUG [ImapConnection-50098] davmail  - > 2 BAD unable to handle request: null
2020-04-01 11:06:23,432 INFO  [ImapConnection-50098] davmail.connection  - DISCONNECT - 127.0.0.1:50098 
2020-04-01 11:06:23,435 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
2020-04-01 11:06:23,436 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:50100 
2020-04-01 11:06:23,681 DEBUG [ImapConnection-50100] davmail.exchange.ExchangeSession  - Test configuration status: 401
2020-04-01 11:06:23,682 DEBUG [ImapConnection-50100] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE SPECIAL-USE] IMAP4rev1 DavMail 5.4.0-trunk server ready
2020-04-01 11:06:23,685 DEBUG [ImapConnection-50100] davmail  - < 1 authenticate LOGIN
2020-04-01 11:06:23,686 DEBUG [ImapConnection-50100] davmail  - > + *********
2020-04-01 11:06:23,687 DEBUG [ImapConnection-50100] davmail  - < *********==
2020-04-01 11:06:23,687 DEBUG [ImapConnection-50100] davmail  - > + **********
2020-04-01 11:06:23,688 DEBUG [ImapConnection-50100] davmail  - < ********
2020-04-01 11:06:23,689 DEBUG [ImapConnection-50100] davmail.exchange.ExchangeSession  - Got session davmail.exchange.ews.EwsExchangeSession@2aef998 from cache
2020-04-01 11:06:23,875 INFO  [ImapConnection-50100] davmail.connection  - LOGON - 127.0.0.1:50100 <email@address>
2020-04-01 11:06:23,876 DEBUG [ImapConnection-50100] davmail  - > 1 OK Authenticated
2020-04-01 11:06:23,878 DEBUG [ImapConnection-50100] davmail  - < 2 select "INBOX"
2020-04-01 11:06:24,220 DEBUG [ImapConnection-50100] davmail.imap.ImapConnection  - *
2020-04-01 11:06:25,259 DEBUG [ImapConnection-50100-LoadFolder] davmail  - Downloaded 130 KBytes from /ews/exchange.asmx
2020-04-01 11:06:25,330 DEBUG [ImapConnection-50100-LoadFolder] davmail  - Downloaded 262 KBytes from /ews/exchange.asmx
2020-04-01 11:06:25,400 DEBUG [ImapConnection-50100-LoadFolder] davmail  - Downloaded 391 KBytes from /ews/exchange.asmx
2020-04-01 11:06:25,482 DEBUG [ImapConnection-50100-LoadFolder] davmail  - Downloaded 523 KBytes from /ews/exchange.asmx
2020-04-01 11:06:25,553 DEBUG [ImapConnection-50100-LoadFolder] davmail  - Downloaded 654 KBytes from /ews/exchange.asmx
2020-04-01 11:06:25,553 ERROR [ImapConnection-50100-LoadFolder] davmail.exchange.FolderLoadThread  - java.lang.NumberFormatException: null null
java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:758)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:680)
	at davmail.exchange.ews.EwsExchangeSession.searchMessages(EwsExchangeSession.java:664)
	at davmail.exchange.ExchangeSession.searchMessages(ExchangeSession.java:314)
	at davmail.exchange.ExchangeSession$Folder.loadMessages(ExchangeSession.java:1184)
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:46)
2020-04-01 11:06:25,554 DEBUG [ImapConnection-50100] davmail.exchange.FolderLoadThread  - Still loading INBOX (7045 messages)
2020-04-01 11:06:25,554 ERROR [ImapConnection-50100] davmail  - null
java.io.IOException: null
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:51)
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Long.parseLong(Long.java:655)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:758)
	at davmail.exchange.ews.EwsExchangeSession.searchItems(EwsExchangeSession.java:680)
	at davmail.exchange.ews.EwsExchangeSession.searchMessages(EwsExchangeSession.java:664)
	at davmail.exchange.ExchangeSession.searchMessages(ExchangeSession.java:314)
	at davmail.exchange.ExchangeSession$Folder.loadMessages(ExchangeSession.java:1184)
	at davmail.exchange.FolderLoadThread.run(FolderLoadThread.java:46)
2020-04-01 11:06:25,554 DEBUG [ImapConnection-50100] davmail  - > 2 BAD unable to handle request: null
2020-04-01 11:06:25,554 INFO  [ImapConnection-50100] davmail.connection  - DISCONNECT - 127.0.0.1:50100 
```

**Comment by mguessan** [comment]
I fixed the NullPointerException... However I hadn't noticed you are not on a Microsoft provided solution (Exchange or Office 365), I am afraid that the amazon implementation does not provide the imapUid field used by DavMail to implement IMAP gateway => this will probably *not* work.
=> would need to find another way to track message ids specific to AWS.

**Comment by tobiasgraf** [comment]
I see, so I'm out of luck for now :(

If I can help with this let me know.

**Comment by mguessan** [comment]
Thanks for your feedback, closing outdated ticket.
